---
# Full initial setup
# Usage: ansible-playbook setup.yml --ask-vault-pass
# Skip optional roles: ansible-playbook setup.yml --ask-vault-pass --skip-tags vpn,st_link,label_printer

- name: Setup devices
  hosts: devices
  become: true

  vars_files:
    - vault.yml

  roles:
    - role: eledio.services.common
    - role: eledio.services.install_uv
    - role: eledio.services.vpn
      tags: vpn
    - role: eledio.services.st_link
      tags: st_link
    - role: eledio.services.label_printer
      tags: label_printer
    - role: app
